using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MakeGenrePlaylist
{
    internal static class Program
    {
        private static void Main(string[] args)
        {
            if (args is null)
            {
                throw new ArgumentNullException(nameof(args));
            }

            string[] files = {
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Moments Of Peace\\05 Romancing The Passion.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Moments Of Peace\\09 In Her Beauty.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Music For Intimacy\\07 Mystery Of Love.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Music For Intimacy\\10 Tender Thoughts.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Music For Intimacy\\11 Intimate Harmonies.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Música Para Hacer El Amor\\01 La Doma.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Música Para Hacer El Amor\\02 Descanso De Grulla.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Música Para Hacer El Amor\\03 Mar Profundo.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Música Para Hacer El Amor\\04 Flor De Loto.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Música Para Hacer El Amor\\05 La Catapulta.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Música Para Hacer El Amor\\06 Dos Peces.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Música Para Hacer El Amor\\07 La Torre.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Música Para Hacer El Amor\\08 La Libélula.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Música Para Hacer El Amor\\09 Caballos Salvajes.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Música Para Hacer El Amor\\10 Leche Y Miel.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Encanto\\02 Costa De La Luz.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Encanto\\03 Magic City.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Encanto\\04 To The Sea.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Encanto\\05 Morning Star.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Encanto\\07 Rhyme Of The Ancient Forest.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Encanto\\08 Ocaso.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Encanto\\09 Encanto.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Encanto\\10 Island Song.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Danny Wright\\Autumn Dreams\\09 Shell Island.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Danny Wright\\Autumn Dreams\\11 Friends.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Danny Wright\\Do You Live, Do You Love\\02 Heaven's Love.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Danny Wright\\Do You Live, Do You Love\\04 Hayden's Spirit.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Danny Wright\\Do You Live, Do You Love\\05 Forever.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Danny Wright\\Moods of Indigo\\01 Wings of Hope.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Danny Wright\\Moods of Indigo\\02 Moods of Indigo.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Danny Wright\\Moods of Indigo\\03 Cipolla.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Danny Wright\\Moods of Indigo\\05 Sunday Regatta.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Danny Wright\\Shadows\\06 Song For Lea.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Danny Wright\\Shadows\\07 Always And Forever.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Forever Love\\05 Sunrise.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Forever Love\\07 Shrouded By Mist.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Forever Love\\09 Lady In The Morning.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\French Kiss\\01 Tu Es Le Seul.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\French Kiss\\04 Mon Amour.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\French Kiss\\08 L'ombre El Le Diable.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\French Kiss\\10 Le Mirage.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\For Your Life - For My Love\\07 Satie_ Gnossienne #1.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kevin Kern\\Endless Blue Sky\\01 Joy Of The Journey.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kevin Kern\\Endless Blue Sky\\02 Velvet Green.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kevin Kern\\Endless Blue Sky\\03 Endless Blue Sky.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kevin Kern\\Endless Blue Sky\\05 Light Spirit.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kevin Kern\\Endless Blue Sky\\08 Caring Friend.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kevin Kern\\Endless Blue Sky\\09 Wending Our Way Home.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kevin Kern\\Endless Blue Sky\\10 The Glistening Pond.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kevin Kern\\Endless Blue Sky\\11 Gifts Along The Way.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Beautiful World\\1-01 Simple Gifts.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Beautiful World\\1-02 River's Edge.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Beautiful World\\1-03 Carnivale.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Beautiful World\\1-04 Harvest.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Beautiful World\\1-05 In the Mountain Air.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Beautiful World\\1-06 Noche Pacifica.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Beautiful World\\1-07 Rainbow Sky.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Beautiful World\\1-08 Wedding Bells.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Beautiful World\\1-09 Free to Fly.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Beautiful World\\1-11 Countryside.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Beautiful World\\1-12 Romance Sur La Seine.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Believe\\01 Sunshine In The Rain.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Believe\\02 The Road Before Us.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Believe\\03 Daybreak.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Believe\\04 As The River Flows.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Believe\\08 Passage Of Time.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Believe\\09 Fireflies.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Believe\\10 Possibilities.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Believe\\11 Thinking Of You.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\No Words\\01 Rocket To The Moon.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\No Words\\03 Open Doors.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\No Words\\05 Wanderlust.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\No Words\\06 Heartland.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\No Words\\07 Borders.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\No Words\\08 Still.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\No Words\\09 American Dream.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\No Words\\12 So Long.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Pure Jim Brickman\\01 If You Believe.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Pure Jim Brickman\\02 Journey.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Pure Jim Brickman\\05 Crossroads.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Pure Jim Brickman\\06 You Never Know.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Pure Jim Brickman\\07 By Chance.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Pure Jim Brickman\\09 Bittersweet.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Pure Jim Brickman\\12 Picture This.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Pure Jim Brickman\\15 Another Tuesday Morning.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\The Gift\\12 Dreams Come True.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\The Romance Of Jim Brickman\\01 Angel Eyes.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\The Romance Of Jim Brickman\\02 Fireside.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\The Romance Of Jim Brickman\\03 Meant To Be.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\The Romance Of Jim Brickman\\05 Course Of Love.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\The Romance Of Jim Brickman\\07 Dream Come True.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\The Romance Of Jim Brickman\\08 Devotion.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\The Romance Of Jim Brickman\\10 Shades Of White.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\The Romance Of Jim Brickman\\11 The Promise.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\The Romance Of Jim Brickman\\12 Part Of My Heart.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Unspoken\\01 Glory.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Unspoken\\02 Cloudy Day.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Unspoken\\03 Sudden Inspiration.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Unspoken\\04 New Beginnings.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Unspoken\\05 Whisper.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Unspoken\\07 The Crossing.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Unspoken\\08 Flying High.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Unspoken\\09 Unspoken.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Unspoken\\10 First Dance.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Unspoken\\11 Far Away From Home.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Unspoken\\12 Timeless.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Unspoken\\13 Blessed.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Piano Therapy\\03 One True Love.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Piano Therapy\\07 Precious Moments.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Smooth Moods\\03 Curves Ahead.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Smooth Moods\\10 Are You Part Of Me.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Smooth Moods\\12 Piano In The Dark.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Rendezvous Lounge 2\\01 Endless Road.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Rendezvous Lounge 2\\04 Flotation.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Rendezvous Lounge 2\\07 Spring Lake.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Rendezvous Lounge 2\\08 El Alba.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Rendezvous Lounge 2\\09 Can You Feel It.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Rendezvous Lounge 2\\11 Wishful Walk.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\04 Amor-Ruiz-Mendez.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\06 At 2 In The Morning.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\08 Body and Soul.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\09 Brazil.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\101 Welcoming - Michael Manringwav.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\13 Cool It Down.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\14 Cop Files (Sensual Rock).m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\15 Desafinado.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\21 Driving - Will Ackerman.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\25 Romantica - Erotic Moods.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\26 Take Me - Erotic Moods.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\28 Coda - Erotic Moods.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\29 TheDream - Erotic Moods.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\31 Breathe With Me - Erotic Moods.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\32 Moving Pictures - Erotic Moods.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\37 Fragile.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\55 Love Will Follow.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\57 Magic is the Moonlight-Grever Pas.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\59 Midnight Magic.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\65 Ocean Breeze.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\66 On Sunday Afternoon.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\70 Paradise.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\71 Partners In Crime(Instrumental) -.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\73 Perfidia.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\75 Rain Forest.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\79 'Round Midnight.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\80 Santa Maria.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\81 Seaside Jam.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\82 Sir Mitch.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\86 Spanish Nights.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\88 Stranger on the Shore.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\The Very Best Of Erotic Moods\\04 Morocco (Electronica).m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\The Very Best Of Erotic Moods\\05 For Want Of Her (Electronica).m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\The Very Best Of Erotic Moods\\07 My Beloved (Electronica).m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\The Very Best Of Erotic Moods\\12 Majorca (Electronica).m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\The Very Best Of Erotic Moods\\13 Pacifica (Electronica).m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Windham Hill Sampler '96\\07 Jenny's Room.m4a",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kurt Brunus\\Horny & Saxy\\01 Sun Rise.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kurt Brunus\\Horny & Saxy\\02 Dreams.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kurt Brunus\\Horny & Saxy\\03 Warm Winter Night.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kurt Brunus\\Horny & Saxy\\04 Sunset in St. Thomas.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kurt Brunus\\Horny & Saxy\\06 Sax Song.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kurt Brunus\\Horny & Saxy\\08 Groovin On.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kurt Brunus\\Horny & Saxy\\09 My Philosophy.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kurt Brunus\\Horny & Saxy\\10 K-Groove.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Kurt Brunus\\Horny & Saxy\\11 Come Again.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\50 Shades of Grey\\Adagio Classical.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\50 Shades of Grey\\Nocturne No. 1 in B flat minor, Op. 9-1 Classical.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\E'Sensual\\09 Race Thru The Clouds (Originally from the album 'Bedouins Paradise').mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\E'Sensual\\10 Rascalette (Originally from the album 'Soul Of My Own').mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\E'Sensual\\12 Neptune's Beach (Originally from the album 'Bedouins Paradise').mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\E'Sensual\\13 Surrender, My Heart (Originally from the album 'Soul Of My Own').mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\E'Sensual\\15 Duende (Originally from the album 'Soul Of My Own').mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\E'Sensual\\01 The Chase (Originally from the album 'Zebra').mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\E'Sensual\\02 Grey Mist At Dawn (Originally from the album 'Zebra').mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\E'Sensual\\03 Animal Attraction (Originally from the album 'Zebra').mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\E'Sensual\\05 Taboo You (Originally from the album 'Zebra').mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\E'Sensual\\06 Bunco Man (Originally from the album 'Bedouins Paradise').mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\E'Sensual\\07 Grevy's Waltz (Originally from the album 'Zebra').mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Picture This\\02 - Sun, Moon & Stars.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Picture This\\03 - Sound Of Your Voice.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Picture This\\05 - Edge Water.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Picture This\\07 - Coming Home.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Picture This\\09 - Secret Love.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Picture This\\10 - First Steps.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Picture This\\12 - Sweet Dreams.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Picture This\\13 - Hero's Dream (Bonus Track).mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Soothe, Vol. 4- Subzero - Sounds That Spark the Senses\\03 Poolside Chill.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Soothe, Vol. 4- Subzero - Sounds That Spark the Senses\\04 Drive North.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Soothe, Vol. 4- Subzero - Sounds That Spark the Senses\\05 On the Rocks.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Soothe, Vol. 4- Subzero - Sounds That Spark the Senses\\06 Through the Fog.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Soothe, Vol. 4- Subzero - Sounds That Spark the Senses\\07 Permafrost.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Soothe, Vol. 4- Subzero - Sounds That Spark the Senses\\08 Served Chilled.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Soothe, Vol. 4- Subzero - Sounds That Spark the Senses\\09 Desert Ice.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Soothe, Vol. 4- Subzero - Sounds That Spark the Senses\\10 Dancing Snowlight.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Soothe, Vol. 4- Subzero - Sounds That Spark the Senses\\11 Midnight Glacier.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Soothe, Vol. 4- Subzero - Sounds That Spark the Senses\\12 Light a Candle.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Soothe, Vol. 4- Subzero - Sounds That Spark the Senses\\13 Funky Flute.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Soothe, Vol. 4- Subzero - Sounds That Spark the Senses\\02 Cool Vibes.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Soothe, Vol. 4- Subzero - Sounds That Spark the Senses\\01 Starbeam.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Pure Romance\\04 Together Again.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Jim Brickman\\Pure Romance\\05 Fields Of Gold.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\02 - La Paloma.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\03 - Tango Espanol.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\04 - Spanish Love Song.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\07 - Estrellita.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\13 - La Cumparsita.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\14 - Solo Guitar.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\15 - Barcelona Rain.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\16 - Andante.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\17 - Bolero.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\18 - Guitar Meditation.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\19 - Adelina.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\21 - Allegro.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\22 - Tango El Cid.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\23 - Sweet Guitar.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\24 - Etude Con Spirito.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\25 - Cielito Lindo.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\26 - Soft Spanish Guitar.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\27 - Buenos Noches.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\28 - Breaking Dawn.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\05 - Gypsy Guitar.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Dinner Music, Spanish Restaurant Music, Sp\\12 - Espanol Folk Song.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Guitar\\01 Bamboleo.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Guitar\\02 Spanish Eyes.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Guitar\\03 Cuando Caliente el Sol.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Guitar\\04 Rodrigo's Guitar Concerto.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Guitar\\05 Spain.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Guitar\\07 Recuerdos.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Guitar\\12 Oye Mi Canto.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Guitar\\13 Solamente una Vez.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Guitar\\14 Juanita.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Spanish Guitar\\15 Quizas Quizas Quizas.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\50 Shades of Grey\\Adagio Classical.mp3",
            "\\\\MCCOY-NAS\\Public\\All Family Stuff\\Vana's Music\\Romance\\50 Shades of Grey\\Nocturne No. 1 in B flat minor, Op. 9-1 Classical.mp3"
            };
            ArrayList genreFiles = new ArrayList(files);
            Console.Write("Creating Playlist File...");
            XmlHelper.CreatePlaylist("Romance", Path.Combine(@"\\MCCOY-NAS\Public\All Family Stuff\Vana's Music\", "Romance.wpl"), genreFiles);
            Console.WriteLine("Done!");

            //const string path = @"\\MCCOY-NAS\Public\All Family Stuff\Vana's Music\";
            //const string searchPattern = "*.m4a|*.mp3|*.mp4|*.wav|*.wma|*.aac";
            //const string fileProperty = "Genre";
            //const string filePropertyValue = "Romance";
            //Console.Write("Finding All Music Files...");
            //ArrayList musicFiles = FileHelper.GetFilesBySearchPattern(path, searchPattern, SearchOption.AllDirectories);
            //Console.WriteLine($"Found {musicFiles.Count} Files!");
            //Console.Write($"Finding All {filePropertyValue} Files...");
            //ArrayList genreFiles = FileHelper.GetFilesByProperty(musicFiles, fileProperty, filePropertyValue);
            //Console.WriteLine($"Found {genreFiles.Count} Files!");
            //Console.Write("Creating Playlist File...");
            //XmlHelper.CreatePlaylist("Romance", Path.Combine(path, "Romance.wpl"), genreFiles);
            //Console.WriteLine("Done!");
        }
    }
}
